# Generated by Django 5.0.14 on 2026-01-02 11:22

from django.db import migrations


def create_owner_memberships(apps, schema_editor):
    """Create OWNER memberships for existing projects."""
    Project = apps.get_model('hub', 'Project')
    ProjectMembership = apps.get_model('hub', 'ProjectMembership')
    User = apps.get_model('auth', 'User')

    for project in Project.objects.all():
        if project.created_by:
            # Create OWNER membership for project creator if it doesn't exist
            ProjectMembership.objects.get_or_create(
                project=project,
                user=project.created_by,
                defaults={
                    'role': 'owner',
                    'invited_by': project.created_by,
                }
            )
        else:
            # If project has no creator, assign to first superuser
            superuser = User.objects.filter(is_superuser=True).first()
            if superuser:
                ProjectMembership.objects.get_or_create(
                    project=project,
                    user=superuser,
                    defaults={
                        'role': 'owner',
                        'invited_by': superuser,
                    }
                )


def reverse_owner_memberships(apps, schema_editor):
    """Remove all memberships (if rolling back)."""
    ProjectMembership = apps.get_model('hub', 'ProjectMembership')
    ProjectMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_projectmembership'),
    ]

    operations = [
        migrations.RunPython(create_owner_memberships, reverse_owner_memberships),
    ]
