# Generated by Django 5.0.14 on 2026-01-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_webhook'),
        ('hub', '0003_create_owner_memberships'),
    ]

    operations = [
    ]
